version = 0.1
[default.deploy.parameters]
stack_name = "caci-lambda-2023"
resolve_s3 = true
s3_prefix = "caci-lambda-2023"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
